lang: node_js
node_js:
- '7'
branches:
  only:
  - src
before_script:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo generate
after_success:
- "./.travis/deploy.sh"
env:
  global:
    secure: WJq5BG/i2sXNKjJ0/XshHHplXSsaLo0yVpXj/CQRTce25L6d5jC+nClbkvbyDo5nHvJeS9alxqQ8J8bixEKdRkqurR2tr2eZ2zGfhI8xMZZ5eXiffWvPdn0FRlbIWAwllvMLBfaNGSi1Ur7LXcBW3Dqbmvr8rrLK6huqLXDERDDd3kiHrZSv5q1MTyk6aAMMDf4uwBjwOHo10gJ0h8L7ZOyPJZtopWaQq6Qud2FRfZFOJ8YThBkn+c/dqOMZB+QBu6z/8HAAALl3erJmbsLt4CXawrw49LfAOajlQB60+luDX1EDCVOf+6/g7laeytw7mgU3NAuPXdSnrvtGfPR4/1XHfkyGRpQkMe4tk2P6K618UkYetUGDhVWpkLJPIq+8LQiaOMxIr/+aTUT0y4Wardz+jB12OqFI9WrRjw/8YY3XTaRxI/7hFDUN7eVrdSfY+UUiL/MjNsNHmpGrGOUrZn1IKDn2aucUw5FMwCMeWNLZjUMcF83czPZcMU6H9+shQpDqttif76pDLWU3QN68y9vya2Smptgtw1J4VYddXGOS6IlTHlMkX35MhCGfLoevOWNOD54wjE+XXekvd2vXlrKDFJ0RGhFYL8rep0muPQMhF50Pwf1rEevdZC0SX+TdLIXuKU1i2ruxCfBlvL9gWaD+Le1mdfBQ5Wq+VT+tnJ4=
