lang: node_js
node_js:
- '7'
branches:
  only:
  - src
before_script:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo generate
after_success:
- "./.travis/deploy.sh"
env:
  global:
    secure: nqw2OCkC+YUXLlZ+fGFFGYvnh3JfvAKmV7avHZZBy5PW/ut8p/q/anoWgtYjTR5o4nQ+Ng5qFOhcJPajlnKeOOyIpP94dZGffLEiJYxQE18A915qNg8PH7/6HgYttms8KFv0iOGua+0tbBH0d+DfrRDoTOolWr5qZs9uloqWlpE4tW5VbWa6gdFRE/vDBmz879x/pJm4VD9NW+VeQTqEN8vpNUBePZ33ua0xy9jTj0pov/P+yj82d12AL+oU5/BRrNAkz32Lwf0ZxXWtV4IOpf4Ffw8wQBkO/vsKDhwmZorTN64CujmkVcl+W7uSBy25OKz2j0V0JF7WuhsDXG3cCh4gVrUke9x3KWBPRMSc+NFNntpKMu22kAJWk9hBs0JfxaxOT2A7najEra4HwEnR1J7zxsM3rL+9dby2BreNqhgpnalApvf3RODTYDOe4VI1YE3W3X66mLG2n7BPS44Y7uCBoC424MB86IR+FYuIqIK865nmEE/v+oiBFgKdF72zY91BpIPQgz3SabBTOOG8Er/19t/po43y08LjJ83Xq9Qi6JpuXxfbWYlO+iw44XK+/P7snvG2ETSDjK7F66MkiuoXFGBrSJdMP6UG+u3A2Tb/ZQD2jC5294Q5KpQOoHTRpbdFKJZ78Hxraxo3r/BZdXV1dbRSSwZjV1UeOa4G/zw=
